### ISSUE TITLE
Language tour feedback

### ISSUE THREAD

**Issue by FaberVitale** [ascandone/kestrel-lang#7]
[Lang tour](https://github.com/ascandone/kestrel-lang/blob/main/language-tour.md)

### Math ops

For UX reasons, it would be better to not duplicate the math operators.

There are 2 possible better alternatives.

#### 1. Overload operators (Rust, Elm)

+ operator is overloaded and can be used for Int + Int and Float + Float.

Attempting to sum an Int with a Float is a compile time error.

```rust
    let a = 1.0 + 2; // error[E0277]: cannot add an integer to a float ❌
```

An explicit cast is required to sum integers

```rust
    let a = 1.0 + 2 as f32; // compiles ✅
```

#### 2. Numeric promotion (Java approach)
 
In Java 1.0 + 2 Returns 3.0.
Numbers are automatically promoted, when necessary, in binary ops.

See [5.1.3 Narrowing Primitive Conversion](https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html)

### String concat operator

In SQL `<>` is the not equal operator.
It's confusing to use it for string concatenation.

Either +, ++ or :: are better alternatives.

**Comment by ascandone** [comment]
Update 1: `<>` was changed into `++`
Update 2: A simplified version of Haskell's type classes was introduced in https://github.com/ascandone/kestrel-lang/pull/25. So far only the trait [`Show`](https://hackage.haskell.org/package/base-4.19.1.0/docs/Text-Show.html), [`Eq`](https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-Eq.html)  and [`Ord`](https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-Ord.html) are included, but a `Num` type classes might be defined too, in order to solve the `+`, `*`, etc overloading problem.
